/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multibodegas;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Geovani
 */
public class Ventas_Detalle extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas_Detalle
     */
    public Ventas_Detalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txt_ordenventa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_cantidadventa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_costoventa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_idventa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_estatus = new javax.swing.JLabel();
        txt_idempresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_idsucursal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_idserie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_idproducto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_IdProducto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txt_buscar1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txt_idventa1 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_estatus1 = new javax.swing.JLabel();
        txt_IdVentaEn = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_Costo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_Precio = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_Idinventario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_Cantidad = new javax.swing.JTextField();

        jLabel7.setText("Orden Venta:");

        jLabel8.setText("Fecha Venta:");

        jLabel9.setText("Cantidad Venta:");

        jLabel10.setText("Costo Venta:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Venta Detalle:");

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Venta Encabezado:");

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Precio Venta:");

        jLabel11.setText("Ingrese el ID Venta Encabezado:");

        jLabel3.setText("ID Empresa:");

        lbl_estatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel4.setText("ID Sucursal:");

        jLabel5.setText("ID Serie:");

        jLabel6.setText("ID Producto:");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jLabel13.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel13.setText("Id Producto");

        txt_IdProducto.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Venta Detalle:");

        btnModificar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        txt_buscar1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel18.setText("Orden Venta");

        btnBuscar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txt_idventa1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        btnRegistrar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel20.setText("Ingrese el ID Venta Encabezado:");

        jLabel21.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel21.setText("Id Venta Encabezado");

        lbl_estatus1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txt_IdVentaEn.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        txt_IdVentaEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdVentaEnActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel22.setText("Costo Venta");

        txt_Costo.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel23.setText("Precio");

        txt_Precio.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel24.setText("Id Inventario");

        txt_Idinventario.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        txt_Idinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdinventarioActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel14.setText("Cantidad");

        txt_Cantidad.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnRegistrar)
                .addGap(23, 23, 23)
                .addComponent(btnModificar)
                .addGap(19, 19, 19)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_idventa1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(txt_IdVentaEn))
                                    .addComponent(txt_Precio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Costo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Idinventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_IdProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(lbl_estatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_estatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idventa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_IdVentaEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(txt_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Idinventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_IdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)))
                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Codigo que permite modificar registros en la base de datos
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //Codigo que permite consultar registros en la base de datos
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Codigo que permite borrar registros en la base de datos
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Codigo que permite insertar registros en al base de datos
      

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Codigo que permite modificar registros en la base de datos
        try {
            String ID = txt_buscar.getText().trim();

                Connection cn = DriverManager.getConnection(RamaContenedor.BD, RamaContenedor.Usuario, RamaContenedor.Contraseña);
            PreparedStatement pst = (PreparedStatement) cn.prepareStatement("update Venta_Detalle set Orden_Venta = ?, Precio_Venta=?, Cantidad=?, Costo_Venta=?, Id_Inventario=?, Id_Productos=?, Id_Venta_Encabezado=? where ID_VentaEnc = " + ID);

             pst.setString(1, txt_idventa1.getText().trim());
            pst.setString(2, txt_IdVentaEn.getText().trim());
            pst.setString(3, txt_Precio.getText().trim());
            pst.setString(4, txt_Costo.getText().trim());
            pst.setString(5, txt_Idinventario.getText().trim());
            pst.setString(6, txt_IdProducto.getText().trim());
            pst.setString(7, txt_Cantidad.getText().trim());
            pst.executeUpdate();

            txt_buscar.setText("");
             JOptionPane.showMessageDialog(null, "Modificación exitosa");
            

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        //Codigo que permite consultar registros en la base de datos
        try {
                Connection cn = DriverManager.getConnection(RamaContenedor.BD, RamaContenedor.Usuario, RamaContenedor.Contraseña);
            PreparedStatement pst = (PreparedStatement) cn.prepareStatement("select * from Venta_Detalle where ID_VentaEnc = ?");
           pst.setString(1, txt_buscar.getText().trim());
//
          /*  ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_idventa.setText(rs.getString("ID_VentaEnc"));
                txt_idempresa.setText(rs.getString("ID_Empresa"));
                txt_idserie.setText(rs.getString("ID_Serie"));
                txt_idsucursal.setText(rs.getString("ID_Sucursal"));
                txt_idproducto.setText(rs.getString("ID_Producto"));
                txt_ordenventa.setText(rs.getString("Orden_Venta"));
                txt_fecha.setText(rs.getString("Fecha_Venta"));
                

            } else {
                JOptionPane.showMessageDialog(null, "Venta Detalle no registrada.");
            }
*/
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Codigo que permite borrar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(RamaContenedor.BD, RamaContenedor.Usuario, RamaContenedor.Contraseña);
            PreparedStatement pst = (PreparedStatement) cn.prepareStatement("delete from Venta_Detalle where Orden_Venta = ?");

            pst.setString(1, txt_buscar.getText().trim());
            pst.executeUpdate();

             txt_idventa.setText("");
            txt_IdVentaEn.setText("");
            txt_Precio.setText("");
            txt_Costo.setText("");
            txt_Idinventario.setText("");
            txt_IdProducto.setText("");
            txt_Cantidad.setText("");
            

            lbl_estatus.setText("Registro eliminado.");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        //Codigo que permite insertar registros en al base de datos
        try {
             Connection cn = DriverManager.getConnection(RamaContenedor.BD, RamaContenedor.Usuario, RamaContenedor.Contraseña);
          //  PreparedStatement pst = (PreparedStatement) cn.prepareStatement("insert into Venta_Detalle values(?,?,?,?,?,?,?)");
            java.sql.PreparedStatement pst = cn.prepareStatement("insert into Venta_Detalle values(?,?,?,?,?,?,?)");

            pst.setString(1, txt_idventa1.getText().trim());
            pst.setString(2, txt_IdVentaEn.getText().trim());
            pst.setString(3, txt_Precio.getText().trim());
            pst.setString(4, txt_Costo.getText().trim());
            pst.setString(5, txt_Idinventario.getText().trim());
            pst.setString(6, txt_IdProducto.getText().trim());
            pst.setString(7, txt_Cantidad.getText().trim());
           JOptionPane.showMessageDialog(null, "Registro  Guardado");
            pst.executeUpdate();

            txt_idventa.setText("");
            txt_IdVentaEn.setText("");
            txt_Precio.setText("");
            txt_Costo.setText("");
            txt_Idinventario.setText("");
            txt_IdProducto.setText("");
            txt_Cantidad.setText("");
            
            
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txt_IdinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdinventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdinventarioActionPerformed

    private void txt_IdVentaEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdVentaEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdVentaEnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JLabel lbl_estatus1;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Costo;
    private javax.swing.JTextField txt_IdProducto;
    private javax.swing.JTextField txt_IdVentaEn;
    private javax.swing.JTextField txt_Idinventario;
    private javax.swing.JTextField txt_Precio;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_buscar1;
    private javax.swing.JTextField txt_cantidadventa;
    private javax.swing.JTextField txt_costoventa;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_idempresa;
    private javax.swing.JTextField txt_idproducto;
    private javax.swing.JTextField txt_idserie;
    private javax.swing.JTextField txt_idsucursal;
    private javax.swing.JTextField txt_idventa;
    private javax.swing.JTextField txt_idventa1;
    private javax.swing.JTextField txt_ordenventa;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
